version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    labels:
      SERVICE_IGNORE: 'yes'
    extra_hosts:
      - "consul:host-gateway"
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    extra_hosts:
      - "consul:host-gateway"
  http:
    image: nginxdemos/hello:latest
    labels:
      SERVICE_80_NAME: http
      SERVICE_80_CHECK_HTTP: /
      SERVICE_80_CHECK_INTERVAL: 5s
      SERVICE_443_IGNORE: 'yes'
      SERVICE_TAGS: production
    ports:
      - "80"
